export const metaCategories = [
  { value: 'all', label: 'Select Meta' },
  { value: 'animal', label: 'Animal' },
  { value: 'political', label: 'Political' },
  { value: 'sporting', label: 'Sporting' },
  { value: 'celebrity', label: 'Celebrity' },
  { value: 'ai-and-technology', label: 'AI and Technology' },
  { value: 'pop-culture', label: 'Pop Culture' },
  { value: 'food-and-drink', label: 'Food and Drink' },
  { value: 'nature-and-environment', label: 'Nature and Environment' },
  { value: 'historical', label: 'Historical' },
  { value: 'fantasy-and-mythology', label: 'Fantasy and Mythology' },
  { value: 'art-and-design', label: 'Art and Design' },
  { value: 'social-movements', label: 'Social Movements' },
  { value: 'nostalgia', label: 'Nostalgia' },
  { value: 'internet-culture', label: 'Internet Culture' },
  { value: 'science-and-education', label: 'Science and Education' },
  { value: 'holidays-and-seasons', label: 'Holidays and Seasons' },
  { value: 'crypto-specific', label: 'Crypto-Specific' },
  { value: 'emojis-and-emoticons', label: 'Emojis and Emoticons' },
  { value: 'fictional-characters', label: 'Fictional Characters' },
  { value: 'gaming', label: 'Gaming' },
  { value: 'miscellaneous', label: 'Miscellaneous' },
]
